### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by happytodev** [cjmellor/skeleton#6]
Hello,

If I follow exactly you installation process, I have this error : 

<img width="1412" alt="image" src="https://github.com/cjmellor/skeleton/assets/425998/6588c1fd-5b9f-49b3-92de-f811b4561fda">

May be I forgot something ?

**Comment by cjmellor** [comment]
It's a template repo, so no need to require it, just clone it into a directory then run `composer install` then `php build`

**Comment by happytodev** [comment]
Ok, understood ;-)

May be a change of documentation will help ?

For example, by replacing : 

```bash
mkdir my-package

cd my-package

composer require cjmellor/skeleton
```

by 

```bash
git clone https://github.com/cjmellor/skeleton my-package

cd my-package

composer install

php build
```

What do you think ?

**Comment by cjmellor** [comment]
Yes, I absolutely need to re-do the README as it's wrong. I'll get on it though feel free to do a PR 😅

**Comment by happytodev** [comment]
with pleasure.

**Comment by happytodev** [comment]
> Yes, I absolutely need to re-do the README as it's wrong. I'll get on it though feel free to do a PR 😅

Done, feel free to change if something need more precisions.

**Comment by cjmellor** [comment]
Cheers brother!
